# Generated by Django 6.0.4 on 2026-07-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
